stages:
  - test
  - build
  - deploy

code_quality:
  image: node:18.17.1
  stage: test
  before_script:
    - npm ci
  script:
    - npm run eslint
    - npm run stylelint
    - npm run prettier-check
  only:
    - main

build:
  image: node:18.17.1
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - main

deploy:
  image: alpine:latest
  stage: deploy
  before_script:
    - apk update && apk add rsync openssh
    - mkdir ~/.ssh
    - chmod 600 ~/.ssh
    - echo "$SSH_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 600 ~/.ssh/known_hosts
  environment:
    name: production
  resource_group: production
  script:
    - rsync -a --delete dist/ $VPS_PATH
  only:
    - main
